### ISSUE TITLE
Please Add checkbox to load files list instead of doing it by default

### ISSUE THREAD

**Issue by bwolven** [DanPatten/Find-Changesets-by-Comment-2017#1]
Thank you for building this very helpful tool.

I would like to suggest that you add a checkbox to pull the file details instead of doing it automatically.
Hopefully this would speed it up the searching process for cases where the user only needs the changeset associated with a comment and not the changeset file details.

**Comment by DanPatten** [comment]
I did not build the tool, I simply forked the org and updated it to work with VS 2017. I would reccommend contacting the original creator.
